
CREATE TABLE TBLCLIENTE
(CPF_CLIENTE VARCHAR2(80) NOT NULL PRIMARY KEY,
NOME_CLIENTE VARCHAR2(80),
ENDERECO_CLIENTE VARCHAR2(80),
CIDADE_CLIENTE VARCHAR2(80),
UF_CLIENTE VARCHAR2(3),
CEP_CLIENTE VARCHAR2(80),
DDD_CLIENTE VARCHAR2(4),
TELEFONE_CLIENTE VARCHAR2(80),
LIMITECREDITO_CLIENTE NUMBER(6,2),
LIMITEDISPONIVEL_CLIENTE NUMBER(6,2),
);

CREATE TABLE TBLVENDEDOR
(CPF_VENDEDOR VARCHAR2(80) NOT NULL PRIMARY KEY,
NOME_VENDEDOR VARCHAR2(80),
ENDERECO_VENDEDOR VARCHAR2(80),
CIDADE_VENDEDOR VARCHAR2(80),
UF_VENDEDOR VARCHAR2(3),
CEP_VENDEDOR VARCHAR2(80),
DDD_VENDEDOR VARCHAR2(4),
TELEFONE_VENDEDOR VARCHAR2(80),
SALARIOBASE_VENDEDOR NUMBER(6,2),
TAXACOMISSAO_VENDEDOR NUMBER(6,2),
);

CREATE TABLE TBLPEDIDO
(NUMERO_PEDIDO VARCHAR2(80) NOT NULL PRIMARY KEY,
CPF_CLIENTE VARCHAR2(80) FOREIGN KEY,
CPF_VENDEDOR VARCHAR2(80) FOREIGN KEY,
DATAEMISSAO_PEDIDO VARCHAR2(80),
VALOR_PEDIDO NUMBER(6,2),
CONSTRAINT FK_CLIENTE_PEDIDO FOREIGN KEY (CPF_CLIENTE) REFERENCES TBLCLIENTE (CPF_CLIENTE),
CONSTRAINT FK_VENDEDOR_PEDIDO FOREIGN KEY (CPF_VENDEDOR) REFERENCES TBLCLIENTE (CPF_VENDEDOR),
);